version: '2'

services:
  db:
    image: mysql:latest
    hostname: db
    environment:
         - MYSQL_ALLOW_EMPTY_PASSWORD: 1

  pmm_server:
    build: ./
    hostname: pmm_server
    depends_on:
        - db
    ports:
        - "80:80"
    environment:
         - MYSQL_HOST: db
